amenitiesapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('calc.urls')),
    path('user/', include('user.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

'''
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
'''

calc/urls.py
from django import views
from django.urls import path, include
from . import views

app_name = "calc"

urlpatterns = [
    path('', views.index, name='index'),
    path('update', views.update, name='update' ),
    path('upload', views.upload_csv, name='upload_csv'),
    path('media', views.media_file, name='media_file'),
    path('today', views.update_daily, name='update_daily'),
    path('tomorrow', views.tomorrow_amenities, name='tomorrow_amenities'),
    path('longstay', views.longstay, name='longstay'),
    path('special', views.special, name='special'),
    path('day-after',views.day_after, name='day_after'),
    path('months/<str:month>', views.month, name='month'),
    path('delete-CSV/<int:id>', views.delete_media, name='delete_media'),
    path('daily-addson', views.update, name='update'),
    path('total/<str:month>', views.total, name='total'),
   

    # API
    path('code_API', views.code_API, name='code_API'),


]

user/urls.py
from django import views
from django.urls import path, include
from . import views

app_name = "user"

urlpatterns = [
    path("register/",views.register, name="register"),
    path("login/", views.login_user, name="login_user"),
    path("logout/", views.logout_user, name="logout_user"),
    path("profile/", views.profile, name="profile"),

]

calc/models.py
from django.db import models

# Create your models here.

Code_item = {
    ('None', 'None'),
    ('VIP3ME', 'VIP3ME'),
    ('VIP4ME', 'VIP4ME'),
    ('VIP5ME', 'VIP5ME'),
    ('VIP1', 'VIP1'),
    ('VIP2', 'VIP2'),
    ('VIP3', 'VIP3'),
    ('VIP4', 'VIP4'),
    ('VIP5','VIP5'),
    ('VIP6', 'VIP6'),
    ('Presidential', 'Presidential')
}
Day_of_week = {
    ('Monday', 'Monday'),
    ('Tuesday', 'Tuesday'),
    ('Wednesday', 'Wednesday'),
    ('Thursday', 'Thursday'),
    ('Friday', 'Friday'),
    ('Saturday', 'Saturday'),
    ('Sunday', 'Sunday')
}
Special_Choice = {
    ('Birthday cake', 'Birthday cake'),
    ('Aniversary cake', 'Aniversary cake'),
    ('Celebration cake', 'Celebration cake'),
    ('Honeymoon cake', 'Honeymoon cake'),
    ('6" cake', '6" cake'),
    ('8" cake', '8" cake'),
    ('Canapes', 'Canapes'),
    ('Sliced fruit platter', 'Sliced fruit platter'),
    ('Special amenities', 'Special amenities')

}
replanisment_choice = {

}
class Amenity(models.Model):
    big_id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=300)   
    date_of_arrival = models.CharField(max_length=100)
    date_of_departure = models.CharField(max_length=100)
    num_of_fruit = models.IntegerField(default=1, blank=True, null=True)
    day_of_week = models.CharField(max_length=200)
    item_code = models.CharField(
        max_length=200, blank=True, null=True)
    amount = models.IntegerField(default=0, blank=True, null=True)
    special_occasion = models.CharField(max_length=300, choices=Code_item, blank=True, null=True)
    date = models.DateField(auto_now_add=True)

    def __str__(self) -> str:
        return f'{self.name, self.date_of_arrival, self.date}'

class Spacial_Amenities(models.Model):
    big_id = models.BigAutoField(primary_key=True)
    arrival_date = models.DateField()
    day_of_week = models.CharField(max_length=200, choices=Day_of_week, blank=True)
    amenity_type = models.CharField(max_length=250, choices=Special_Choice, blank=True)
    amenity_code = models.CharField(max_length=150, choices=Code_item, blank=True,)
    amenity_amount = models.IntegerField(default=0,blank= False )
    date_of_input = models.DateField(auto_now_add=True)

    def __str__(self) -> str:
        return f'{self.arrival_date,self.day_of_week,self.amenity_type,self.date_of_input }'


class CSVFile(models.Model):
    big_id = models.BigAutoField(primary_key=True, )
    file = models.FileField(upload_to='csv_files/')
    

    def __str__(self) -> str:
        return f'{self.file, self.big_id}'
    
class Amenities_CSV(models.Model):
    big_id = models.BigAutoField(primary_key=True)
    date = models.CharField(max_length=200)
    day_of_week = models.CharField(max_length= 200)
    amenity_code = models.CharField(max_length=150)
    iventory = models.CharField(max_length=200, default= 100)
    reserved = models.CharField(max_length=200, default= 0)
    date_of_input = models.DateField(auto_now_add=True)

    def __str__(self) -> str:
        return f'{self.date, self.amenity_code, self.reserved, self.date_of_input}'

class Replenishment(models.Model):
    amenity_replen = models.CharField(max_length = 300,)
    amount_day = models.IntegerField(default=0, blank=True)
    date_of_input = models.DateField(auto_now_add=True)

    def __str__(self) -> str:
        return f'{self.amenity_replen, self.amount_day, self.date_of_input}'

calc/forms.py
from django import forms
from django.forms import DateInput
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import fields
from django.views.generic.edit import FormView

from .models import *


class registrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


# craete intoform // got the idea from https://stackoverflow.com/questions/3367091/whats-the-cleanest-simplest-to-get-running-datepicker-in-django
class DateInput(forms.DateInput):
    input_type = 'date'


class InputData(forms.ModelForm):

    class Meta:
        model = Amenity

        fields = '__all__'
        # change input to date input
        widgets = {
            'arrival_date': DateInput(),
            'checkout_date' : DateInput()
        }


DAY_CHOICES = [
    ('monday', 'Monday'),
    ('tuesday', 'Tuesday'),
    ('wednesday', 'Wednesday'),
    ('thursday', 'Thursday'),
    ('friday', 'Friday'),
    ('saturday', 'Saturday'),
    ('sunday', 'Sunday'),
]
AMENITY_CODE =[
     ('None', 'None'),
    ('VIP3ME', 'VIP3ME'),
    ('VIP4ME', 'VIP4ME'),
    ('VIP5ME', 'VIP5ME'),
    ('VIP1', 'VIP1'),
    ('VIP2', 'VIP2'),
    ('VIP3', 'VIP3'),
    ('VIP4', 'VIP4'),
    ('VIP5','VIP5'),
    ('VIP6', 'VIP6'),
    ('VIP6', 'Presidential')
]


class UpDateDaily(forms.Form):    
    #class Meta:
        model = Amenities_CSV
        #fields = ['date', 'day_of_week', 'amenity_code', 'inventory', 'reserved']
        date = forms.DateField(required=True, widget=forms.DateInput(format="%d/%m/%Y", attrs={"type": "date"}),
        input_formats=["%d/%m/%Y"])  
        day_of_week = forms.ChoiceField(required=True,choices=DAY_CHOICES, )
        amenity_code = forms.ChoiceField(required=True,choices=AMENITY_CODE, )
        iventory = forms.IntegerField(initial=100, max_value=100)
        reserved = forms.IntegerField(initial=0,min_value=0)
        
        
        
             
        

        





class CSVFileForm(forms.ModelForm):
    class Meta:
        model = CSVFile
        fields = ['file']




class SpecialAmenity(forms.ModelForm):
    class Meta:
        model = Spacial_Amenities
        fields = '__all__'
        widgets = {
            'arrival_date': forms.DateInput(
                attrs={'type': 'date', 'placeholder': 'dd/mm/yyyy (DOB)', 'class': 'form-control'}
            )
        }



        

calc/views.py
from calendar import month
from django.shortcuts import render
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import Group
from django.contrib.auth.models import update_last_login
from django.views.decorators.csrf import csrf_protect
from django.urls import reverse
from django.http import JsonResponse
import csv
import json
import datetime 
from datetime import timedelta 
import datetime as dt
from .login import *

from django.utils.dateparse import parse_date
from django.templatetags.static import static



from .forms import *


# global variebles
time = datetime.datetime.now()
TODAY = time.strftime('%Y'+'-'+'%m'+'-'+'%d')
today = time.strftime('%d'+'/'+'%m'+'/'+'%Y')
ENTRY = Amenities_CSV.objects.all()
YearMounts = {'01': 'January', '02': 'February', '03': 'March', '04': 'April', '05': 'May', '06': 'June',
              '07': 'July', '08': 'Auguest', '09': 'September', '10': 'Octomber', '11': 'November', '12': 'December'}
#DATA_LONG_STAY = LongStay.objects.all()

FRUIT = ['Large fruit', 'Midium fruit','Small fruit','Presidential']
DRINK = ['White wine','Red wine','Champagne', 'Negroni', 'Water']
TURN_DOWN = { 'Monday':'Ginger Florentine',
                'Tuesday':'Vanilla Macaroons', 
                'Wednesday':'Pistachio Finnacier',
                'Thursday':'Lemon drizzle',
                'Friday':'Mini cooies',
                'Saturday':'Vanilla Madeleines',
                'Sunday' :'MIxed seeds and nuts Flapjack',
}
DESSERT = ['Chocolate truffle', 'Macaroons 4pcs', 'Macaroons 8pcs', 'Baklava', 'Maamul', 'Arab amenity']
CODE_AMENITY = {
	'VIP1': ('birthday cake', '' , ''),
	'VIP2': ('Chocolate box', '', ''),
	'VIP3': ('Small fruit bowl', 'florentine', ''),
	'VIP4': ('Medium fruit bowl', '4 macaroons', 'Red Wine'),
	'VIP5': ('Large fruit bowl', '6 macaroons', 'Premium Red Wine'),
	'VIP6': ('Presidential fruit bowl', '8 macaroons', 'Custom Amenities' ),
	'VIP4ME': ('Medium fruit bowl','dates', 'baklava'),
	'VIP3ME': ('Small fruit bowl', 'dates', ''),
	'VIP5ME': ('Large fruit bowl', 'Arabic Inspired Amenity', '')

}


# Create your views here.


# input of csdv file + spacial amenities
def index(request):
    
    if request.user.is_authenticated:
       
            user = request.user.username
            
            #print(time.strftime('%A'))
            #delete all entry of csv file model
            if request.method == 'POST':
            # name = request.POST['day']
                day_name = time.strftime('%A')
                amound = request.POST['amount']
                for k, v in TURN_DOWN.items():
                    if day_name == k:
                        
                        data = Replenishment(amenity_replen=v,amount_day=amound,date_of_input=today)
                        data.save()
                        print(v)

            return render(request, 'calc/index.html', {
                'form': InputData(),
                'form1' : CSVFileForm(),
                'user':user
            })

    else:
        return render(request, 'calc/index.html', {
            'msg': 'You need to login!!!',
            
        })



def upload_csv(request):
    user = request.user.username
    if request.method == 'POST':
        form = CSVFileForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            file = CSVFile.objects.all()  
            print(file)  
 
            for entyr in file: 
                #print(entyr)
                #neeed to work on file path
                file1 = open(('media/'f'{entyr.file}'))
                
                #print(file1)      
                with open ('media/'f'{entyr.file}', 'r') as fi:
                    csvreader = csv.reader(fi)
                    for row in csvreader:
                        for cell in csvreader:
                            #print(row[0], row[1])
                            #print(cell[1], cell[2], cell[4], cell[13],cell[12])
                
                            data = Amenities_CSV(date= cell[1], 
                                    day_of_week=cell[2], amenity_code=cell[4],iventory=cell[13],
                                    reserved=cell[12])
                            print(data)
                            data.save()
                            
                            #file.delete()
                            #break from the loop if not integer 
                            data = CSVFile.objects.all()
                            print(data)

            data_input = Amenities_CSV.objects.all()
            for d in data_input:
                if '/' not in d.date:
                    d.delete()

            # Add additional processing logic if needed
            return render(request, 'calc/index.html', {
        'form': InputData(),
        'form1' : CSVFileForm(),
        'user':user
    })
            #return redirect('index')  # Redirect to a success page
    else:
        form = CSVFileForm()

    return render(request, 'calc/upload_csv.html', {'form': form})


def update_daily(request):

    DATE_OF_SUBMITION = Amenities_CSV.objects.filter(date_of_input=TODAY)
    entry = Amenities_CSV.objects.all()
    replenish = Replenishment.objects.filter(date_of_input=TODAY)
    special_data =[]
    reple = []
    # spaecial input amaenities need to conbaind them
    special_entry = Spacial_Amenities.objects.all()
    for s in special_entry:
        s_date = s.arrival_date.strftime('%d'+'/''%m'+'/'+'%Y')
        if s_date == today:
            special_data.append(s)
    #replenish.delete()
    for en in replenish:
        reple.append(en)   
        #print(s.arrival_date,'-',s_date)
    #print(special_data)
    
    # back to the original operation
    t = datetime.datetime.now() + timedelta(days=1)
    day_tomorrow = t.strftime('%d'+'/'+'%m'+'/'+'%Y')
    Data_for_today =[]
    Count = 0
    data_with_amenity = []
	
    for ent in entry:
       # print(ent.date,' --', today)
        if ent.date == today:
            for key, item in CODE_AMENITY.items():
                if ent.amenity_code == key:
                    Count = Count + 1
            #print(ent)
                    input_date = str(ent.date_of_input)
                    Data_for_today.append({
                    'arrival_date': ent.date,
                    'day_name': ent.day_of_week,
                    'amenity_code': ent.amenity_code,
                    'fruit_amenity': item[0],
                    'dessert_amenity': item[1],
                    'dessert_amenity1': item[2],
                    'iventory': ent.iventory,
                    'reserved': ent.reserved,
                    'input_date': input_date,
                    'today_date': time.strftime('%d'+'/'+'%m'+'/'+'%Y')
                    })

    data_view = []
    data12 = CSVFile.objects.all()
    for d in data12:
        data_view.append({'file': d.file,
                          'id': d.big_id})



    #print(Data_for_today,'-',data_with_amenity)
    #print(entry, '____---',DATE_OF_SUBMITION)
    return render(request, 'calc/today.html',{'data':Data_for_today,
                                              'code': CODE_AMENITY,
                                              'special':special_data,
                                              'today': today,
                                              'replenish': reple,
                                              'media': data_view})


def code_API(request):
    
    JSON_data = []
    entry = Amenities_CSV.objects.all()
    for it in entry:
        
        for key, item in CODE_AMENITY.items():
            if it.amenity_code == key:
               
                input_date = str(it.date_of_input),
                
                JSON_data.append({
                    'big_id': it.big_id,
                    'arrival_date': it.date,
                    'day_name': it.day_of_week,
                    'amenity_code': it.amenity_code,
                    'fruit_amenity': item[0],
                    'dessert_amenity': item[1],
                    'dessert_amenity1': item[2],
                    'iventory': it.iventory,
                    'reserved': it.reserved,
                    'input_date': input_date,
                    'today_date': time.strftime('%d'+'/'+'%m'+'/'+'%Y')
                    })
 

   
    special_entry = Spacial_Amenities.objects.all()
    for sp in special_entry:

          
        date_of_input = sp.arrival_date.strftime('%d'+'/'+'%m'+'/'+'%Y')
        #print(date_of_input)
        JSON_data.append({
                'big_id': sp.big_id,
                'arrival_date': date_of_input,
                'day_name': it.day_of_week,
                'amenity_code': it.amenity_code,
                'fruit_amenity': sp.amenity_type,
                'dessert_amenity':'',
                'dessert_amenity1': '',
                'iventory': '100',
                'reserved': sp.amenity_amount,
                'input_date': date_of_input,
                'today_date': time.strftime('%d'+'/'+'%m'+'/'+'%Y'),

        })
        
    '''           
    data =[]            
    special_entry = Spacial_Amenities.objects.all()
    for sp_it in special_entry:
        for key, item in CODE_AMENITY.items():
            date_input = str(it.date_of_input)
            if sp_it.amenity_code == key:
                
                data.append({
                    'big_id': sp_it.big_id,
                    'arrival_date': sp_it.arrival_date,
                    'day_name': sp_it.day_of_week,
                    'amenity_code': sp_it.amenity_code,
                    'fruit_amenity': item[0],
                    'dessert_amenity': item[1],
                    'dessert_amenity1': item[2],
                    'iventory': '100',

calc/templates/calc/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/style/style.css">
    <title>Document</title>
    <style>
        .body-container {
            margin-top: 10%;
        }
        body{
        background-color: rgb(207, 203, 190);
       
    }
    </style>

    {% block style %}
    {% endblock %}
</head>

<body>
    <nav class="nav ">
        <div class="container">
            <h1 class="logo"><a href="{% url 'calc:index' %}">InterContinental Amenitie App</a></h1>
            <ul>
 
                
               
               
                
                {% if  user.is_authenticated %}
                <li><a href="{% url 'user:logout_user' %}">Logout</a></li>
                                
                {% else %}
                <li><a href="{% url 'user:register' %}">Register</a></li>
                <li><a href="{% url 'user:login_user' %}">Login</a></li>           
                {% endif %}
                
                <!--<li><a href="">Code</a></li>
                <li><a href="contact.html">Contact</a></li>-->
            </ul>
        </div>
    </nav>
    <div class="body-container">
        {% block body %}
        {% endblock %}
    </div>

</body>
<script src="{% static 'js/script.js' %}"></script>
<script src="{% static 'js/details.js' %}"></script>
{% block static %}
{% endblock %}

</html>

calc/templates/calc/index.html
{% extends "calc/base.html" %}
{% load static %}
{% load auth_extras %}

{% block style %}
<link rel="stylesheet" href="/static/style/index.css">
<style>
body{
    background-image: url(https://lh4.googleusercontent.com/wJh4s3sEO5HBwxmRMr1rZImrV3jQHFbC2OYceV0pcRWGwzO2tfR7jzRisn-Tpqx3w0gJWcfdpW_RgE00oSBdVaS8J23LxfqOJ49ZP2u9Ni7qJcHH8x26_YaYqSs8TNBz3h1eUYEE), url(https://ucarecdn.com/dbfbdb78-2419-4a51-9d20-f3ee4651fc64/-/resize/800x/);
        background-position: right bottom, left top;
        background-repeat: no-repeat, no-repeat;
    }
    .holder{
        background-color: transparent;
    }
</style>
{% endblock %}

{% block body %}

{% if not request.user.is_authenticated %}
    <div id="msg"><h1>{{msg}}</h1></div>
{% else %}
    
    <div id="greeting"><h1>Hello:  {{user}}</h1></div>
<div class="spacial" id="spec">
    <a href="{% url 'calc:special' %}">Input Special Amenity</a>
    <a href="{% url 'calc:update' %}"><h6>Update Amenitie List</h6></a><br>
</div>
<div class="todayAm">
    <button class="btnLink"> <a href="{% url 'calc:update_daily' %}"><h6>Today Amenitie</h6></a></button>
    <button class="btnLink"><a href="{% url 'calc:tomorrow_amenities' %}"><h6>Tomorrow Amenitie</h6></a></button>
    <button class="btnLink"><a href="{% url 'calc:day_after' %}"><h6>Day After Amenitie</h6></a></button>
</div>
{% if request.user|has_group:"grm"  or request.user|has_group:"admin"%}
<div class="holder">
    <div class="form-container" >
        <form id="upload" method="post" action="{% url 'calc:upload_csv' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form1.as_p }}
            <button type="submit">Upload CSV</button>
           
        </form>

    </div>
    <div class="form-container" >
        <h3>Replanisment</h3>
        <div class="form">
            <form action="{% url 'calc:index' %}" method="post" enctype="multipart/form-data" id="form">
                {% csrf_token %}
                <!--<input type="date" name="day" id="weekDay">-->
                <input type="number" name="amount" id="amound" min="0" max="100">
                <input type="submit" value="Submit" id="btn">
            </form>
        </div>
    </div>
</div>
{% endif %}
<output id="output"></output>
<div class="archive" id="archive">
    <li><a href="{% url 'calc:month' 'January' %}">January</a></li>
    <li><a href="{% url 'calc:month'  'February' %}">February</a></li>
    <li><a href="{% url 'calc:month' 'March' %}">March</a></li>
    <li><a href="{% url 'calc:month' 'April' %}">April</a></li>
    <li><a href="{% url 'calc:month' 'May' %}">May</a></li>
    <li><a href="{% url 'calc:month' 'June' %}">June</a></li>
    <li><a href="{% url 'calc:month' 'July' %}">July</a></li>
    <li><a href="{% url 'calc:month' 'August' %}">August</a></li>
    <li><a href="{% url 'calc:month' 'September' %}">September</a></li>
    <li><a href="{% url 'calc:month'  'Octomber' %}">Octomber</a></li>
    <li><a href="{% url 'calc:month'  'November' %}">November</a></li>
    <li><a href="{% url 'calc:month' 'December' %}">December</a></li>
</div>
{% endif %}

{% endblock %}
{% block static %}
<script src="{% static 'js/index.js' %}"></script>
{% endblock %}

calc/templates/calc/today.html
{% extends "calc/base.html" %}
{% load static %}

{% block static %}
<script src="{% static 'js/today.js' %}"></script> 
{% endblock %}

{% block style %}
<link rel="stylesheet" href="/static/style/today.css">
{% endblock %}

{% block body %}
{% if user.is_superuser%}
{% for m in media %}
<ul id="files">
    <a href="{% url 'calc:delete_media' m.id %}">
        <li>{{m.file}}-----{{m.id}}</li>
    </a>
</ul>

{% endfor %}
{% endif %}
    
    <h1>Todays arrivals: <p id="today_date">{{today}}</p></h1>

    <div class="item-container">
       
<table style="width:80%">
  <tr>
    <th>Name</th>
    <th>Membership</th>
    <th>Reserved</th>
    <th>Date of Arrival</th>
    <th>Amenities</th>
    <th>Date</th>
  </tr>
  {% for d in data %}
  <tr class="ame">
    {% if d.reserved != '0' %}
        <td><p>{{d.today_date}}</p></td>
        <td >{{d.amenity_code}}</td>
        <td>{{d.reserved}}</td>
        <td>{{d.arrival_date}}</td>  
        <td class="amenities">{{d.fruit_amenity}},<br>{{ d.dessert_amenity}},<br>{{d.dessert_amenity1}}</td>  
        <td>{{d.input_date}}</td>
    {% endif %}
  </tr>
  {% endfor %}
  {% if special  %}
   
  {% for s in special %}
  <tr>
    
    <td><p>{{s.arrival_date}}</p></td>
    <td >{{s.amenity_code}}</td>
    <td>{{s.amenity_amount}}</td>
    <td>{{s.arrival_date}}</td>  
    <td class="amenities">{{s.amenity_type}},<br>{{ d.dessert_amenity}},<br>{{d.dessert_amenity1}}</td>  
    <td>{{s.date_of_input}}</td>
  </tr>
  {% endfor %}
  {% endif %}
  <tr>
    <td>February</td>
    <td style="text-align:right">$80</td>
  </tr>
</table>
{% if replenish %}
{% for en in replenish %}
   <h5>Replenishment for today:</h5> <p>{{en.amenity_replen}} : {{en.amount_day}}</p>
{% endfor %}
{% endif %}

</div>
<div class="total">
    <ul id="total">
        <li></li>
    </ul>
</div>

<div class="longstay">
    <div class="card_longsaty">
        <button class="BtnLink"><a href="{% url 'calc:tomorrow_amenities' %}">Tomorrow Amenity</a></button>
        <button class="BtnLink"><a href="{% url 'calc:day_after' %}">Day after Tomorrow</a></button>
        
    </div>
</div>

{% endblock %}

calc/templates/calc/tomorrow.html
{% extends "calc/base.html" %}
{% load static %}


{% block static %}
<script src="{% static 'js/tomorrow.js' %}"></script>
{% endblock %}

{% block style %}
<link rel="stylesheet" href="/static/style/tomorrow.css">
<link rel="stylesheet" href="/static/style/today.css">
{% endblock %}



{% block body %}
{% if not request.user.is_authenticated %}
    <div id="msg"><h1>{{msg}}</h1></div>
{% else %}
            {% if date1 %}
                <h1 id="words">{{date1}} <h1 id="date">{{date}}</h1></h1>
            {% else %}   
                <h1 id="words">Tomorrow arrivals: <h1 id="date">{{date}}</h1></h1>
            {% endif %}
        <div class="item-container">
        
    <table >
    <tr>
        <th>Name</th>
        <th>Membership</th>
        <th>Reserved</th>
        <th>Date of Arrival</th>
        <th>Amenities</th>
        <th>Date</th>
    </tr>
    {% for d in data %}
    <tr>
        {% if d.reserved != '0' %}
            <td>{{d.arrival_date}}</td>
            <td >{{d.amenity_code}}</td>
            <td>{{d.reserved}}</td>
            <td>{{d.arrival_date}}</td>  
            <td class="amenities">{{d.fruit_amenity}},<br>{{ d.dessert_amenity}},<br>{{d.dessert_amenity1}}</td>  
            <td>{{d.input_date}}</td>
        {% endif %}
    </tr>
    {% endfor %}
    {% if special %}
    {% for s in special %}
    <tr>
        {% if d.reserved != '0' %}
            <td>{{s.arrival_date}}</td>
            <td >{{s.amenity_code}}</td>
            <td>{{s.reserved}}</td>
            <td>{{s.arrival_date}}</td>  
            <td class="amenities">{{s.amenity_type}}</td>  
            <td>{{s.input_date}}</td>
        {% endif %}
    </tr>
    {% endfor %}
    {% endif %}
    <tr>
        <td>February</td>
        <td style="text-align:right">$80</td>
    </tr>
    </table>


    </div>
    <div class="total">
        <ul id="total">
            <li></li>
        </ul>
    </div>

    <div class="longstay">
        <div class="card_longsaty">
            <button class="BtnLink" id="btnLinkReverse"><a href="{% url 'calc:tomorrow_amenities' %}" class="BtnLinkElement">Tomorrow Amenity</a></button>
            <button class="BtnLink" ><a href="{% url 'calc:update_daily' %}" class="BtnLinkElement">Today amenities</a></button>
            <button class="BtnLink"><a href="{% url 'calc:day_after' %}" class="BtnLinkElement">Day after Tomorrow</a></button>
        </div>
    </div>
{% endif %}
{% endblock %}